spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    include:
      - aws
      - credentials

  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  url: http://localhost:8080
  version: 1.0.0
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC
  paths-to-match:
    - /post/**
    - /member/**
    - /like/**

jwt:
  header: ${HEADER}
  prefix: ${PREFIX}
  secret: ${SECRET}
  exp:
    access: ${ACCESS}
    refresh: ${REFRESH}
